/**
 * Type definitions for the feature flags system
 *
 * This file is automatically generated from the main module.
 * Import types and functions from '@/features' instead.
 */

/**
 * Supported environment names
 */
export type Environment = "local" | "integration" | "prod";

/**
 * Available feature flags
 *
 * Current flags:
 * - signup: User registration feature
 * - resetPassword: Password reset feature
 */
export type FeatureFlag = "signup" | "resetPassword";

/**
 * Configuration for a single feature flag
 */
export interface FeatureFlagConfig {
  /**
   * Default state when environment is not explicitly configured
   */
  defaultEnabled: boolean;

  /**
   * Environment-specific overrides
   */
  environments: {
    local?: boolean;
    integration?: boolean;
    prod?: boolean;
  };
}

/**
 * Complete feature flags configuration
 */
export type FeatureFlagsConfig = Record<FeatureFlag, FeatureFlagConfig>;

/**
 * Checks if a feature flag is enabled in the current environment
 *
 * @param flagName - The name of the feature flag to check
 * @returns true if the feature is enabled, false otherwise
 */
export function isFeatureEnabled(flagName: FeatureFlag): boolean;

/**
 * Gets all feature flags and their current states
 *
 * @returns Object with all feature flags and their enabled state
 */
export function getAllFeatureFlags(): Record<FeatureFlag, boolean>;

/**
 * Gets the current environment name
 *
 * @returns The current environment name
 */
export function getEnvironment(): Environment;

/**
 * Creates a Response object for a disabled feature (403 Forbidden)
 *
 * @param featureName - Human-readable name of the feature
 * @returns Response object with 403 status
 */
export function createFeatureDisabledResponse(featureName: string): Response;

/**
 * Checks if a feature is enabled and returns a Response if not
 *
 * @param flagName - The feature flag to check
 * @param featureName - Human-readable name for the error message
 * @returns Response object if feature is disabled, null if enabled
 */
export function requireFeatureEnabled(flagName: FeatureFlag, featureName: string): Response | null;
