/// <reference types="astro/client" />

import type { SupabaseClient, Session, User } from "@supabase/supabase-js";
import type { Database } from "./db/database.types.ts";

declare global {
  namespace App {
    interface Locals {
      supabase: SupabaseClient<Database>;
      session: Session | null;
      user: User | null;
    }
  }
}

// Note: Environment variable types are now automatically generated by astro:env
// based on the schema defined in astro.config.mjs
// No need to manually declare ImportMetaEnv anymore
